#---------------------------sensor---------------------------
create_clock -period 20.000 -name cam_pclk_i [get_ports cam_pclk_i]
set_property PACKAGE_PIN W19 [get_ports cam_pclk_i]
set_property PACKAGE_PIN P14 [get_ports cam_vsync_i]
set_property PACKAGE_PIN R14 [get_ports cam_href_i]
set_property PACKAGE_PIN W20 [get_ports cam_xclk_o]
set_property PACKAGE_PIN W17 [get_ports {cam_data_i[0]}]
set_property PACKAGE_PIN V17 [get_ports {cam_data_i[1]}]
set_property PACKAGE_PIN Y19 [get_ports {cam_data_i[2]}]
set_property PACKAGE_PIN Y18 [get_ports {cam_data_i[3]}]
set_property PACKAGE_PIN R17 [get_ports {cam_data_i[4]}]
set_property PACKAGE_PIN P16 [get_ports {cam_data_i[5]}]
set_property PACKAGE_PIN R16 [get_ports {cam_data_i[6]}]
set_property PACKAGE_PIN P15 [get_ports {cam_data_i[7]}]
set_property PACKAGE_PIN N13 [get_ports cam_scl]
set_property PACKAGE_PIN N14 [get_ports cam_sda]

set_property IOSTANDARD LVCMOS18 [get_ports cam_vsync_i]
set_property IOSTANDARD LVCMOS18 [get_ports cam_href_i]
set_property IOSTANDARD LVCMOS18 [get_ports cam_pclk_i]
set_property IOSTANDARD LVCMOS18 [get_ports cam_xclk_o]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {cam_data_i[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS18 [get_ports cam_sda]
set_property PULLUP true [get_ports cam_scl]
set_property PULLUP true [get_ports cam_sda]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_i]

create_clock -period 40.000 -name sysclk [get_ports sys_clk_i]
set_property PACKAGE_PIN V4 [get_ports sys_clk_i]
set_property IOSTANDARD SSTL135 [get_ports sys_clk_i]

set_property PACKAGE_PIN M15 [get_ports phy_rst_o]
set_property IOSTANDARD LVCMOS25 [get_ports phy_rst_o]
###############-----ETH1----#################
### -----------------RX------------------###
set_property PACKAGE_PIN L19 [get_ports PHYA_rgmii_rxc]
set_property PACKAGE_PIN L20 [get_ports PHYA_rgmii_rx_ctl]
set_property PACKAGE_PIN N20 [get_ports {PHYA_rgmii_rxd[0]}]
set_property PACKAGE_PIN M20 [get_ports {PHYA_rgmii_rxd[1]}]
set_property PACKAGE_PIN K13 [get_ports {PHYA_rgmii_rxd[2]}]
set_property PACKAGE_PIN K14 [get_ports {PHYA_rgmii_rxd[3]}]
### -----------------TX------------------###
set_property PACKAGE_PIN L15 [get_ports PHYA_rgmii_txc]
set_property PACKAGE_PIN L14 [get_ports PHYA_rgmii_tx_ctl]
set_property PACKAGE_PIN M13 [get_ports {PHYA_rgmii_txd[0]}]
set_property PACKAGE_PIN L13 [get_ports {PHYA_rgmii_txd[1]}]
set_property PACKAGE_PIN K17 [get_ports {PHYA_rgmii_txd[2]}]
set_property PACKAGE_PIN J17 [get_ports {PHYA_rgmii_txd[3]}]

set_property SLEW FAST [get_ports PHYA_rgmii_txc]
set_property SLEW FAST [get_ports PHYA_rgmii_tx_ctl]
set_property SLEW FAST [get_ports {PHYA_rgmii_txd[3]}]
set_property SLEW FAST [get_ports {PHYA_rgmii_txd[2]}]
set_property SLEW FAST [get_ports {PHYA_rgmii_txd[1]}]
set_property SLEW FAST [get_ports {PHYA_rgmii_txd[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports PHYA_rgmii_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports PHYA_rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_rxd[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports PHYA_rgmii_txc]
set_property IOSTANDARD LVCMOS25 [get_ports PHYA_rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PHYA_rgmii_txd[0]}]

#bit compress
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins cha_inst/system_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks cam_pclk_i]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins cha_inst/system_i/mig_7series_0/u_system_mig_7series_0_0_mig/u_ddr3_infrastructure/gen_mmcm.mmcm_i/CLKFBOUT]] -group [get_clocks -of_objects [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_15_625]
